### ISSUE TITLE
JS and JVM response inconsistency in serialization and conversion requests

### ISSUE THREAD

**Issue by deiteris** [aml-org/als#611]
Your issue may already be reported! Please search on Github issues before creating one.

* **I'm submitting a ...**
    - [x] bug report
    - [ ] feature request
    - [ ] question
    - [ ] other

* **What is the current behavior?**

When I was adopting `als-node-client`, I noticed that these two requests have a bit different responses:
1. `conversion` response has `model: string` in JVM, while in JS it is `document: string`.
2. `serialization` response contains `model: string` (the model is stringified json) in JVM, while in JS it is `model: Array<Object>` in JS (the model is already parsed json).

* **Please provide stack traces/logs and the failing JSON rpc message if possible**

Trace from JS 4.1.0: https://pastebin.com/rbBZh9UF
Trace from JVM 4.0.0: https://pastebin.com/L9j73ibE

* **What is the expected behavior?**

This should be either documented, if this is expected behavior, or responses should have identical structure.

* **What is the motivation/use case for changing the behavior? (for feature requests)**

* **Please tell us about your environment:**

    - ALS Version: 4.1.0 (JS), 4.0.0 (JVM)
    - ALS Distribution: JVM and JS
    - OS: Windows 10 21H1

* **Other information** (e.g. detailed explanation, stack traces, related issues, workarounds, links for us to have context, eg. StackOverflow, Gitter, etc)

**Comment by llibarona** [comment]
Hi @deiteris 
I uploaded the ticket to: https://www.mulesoft.org/jira/browse/ALS-1698

Here I changed the `document` for `model` in JS as it should be: `GH-610/relatedInformationChange-js` commit `efe95c42a33c6e0dc69a1bc30e99a5fdd54d012b`

Regarding the different return types, we will add the corresponding documentation.
The reason this is different from JS and JVM is for optimization on the JS clients, with large API the serialized string gave our internal client performance issues, thus we provided a JSObject in order to optimize resources. (You should be able to pass this object to API Console if that is your intention)
If you need the String let me know and I will see if I can create a story to address this need

**Comment by deiteris** [comment]
Hi @llibarona,

> The reason this is different from JS and JVM is for optimization on the JS clients, with large API the serialized string gave our internal client performance issues, thus we provided a JSObject in order to optimize resources. (You should be able to pass this object to API Console if that is your intention)
> If you need the String let me know and I will see if I can create a story to address this need

Okay, there is no need for string, I just wanted to clarify this so I can make appropriate change. I'll just parse the JSON for JVM version before sending it to the API Console.

**Comment by llibarona** [comment]
Great! then we will just add the documentation and no new message

**Comment by llibarona** [comment]
Hi @deiteris, this issue will be solved in ALS 5.0.0 due to interface changes (we need to change both the request and response parameters, as they do not coincide with their JVM counterparts)
We are currently releasing 4.1.1 which only contains a bump in AMF version, but soon we will release 4.2.0 which will contain (among other things) the fix for GH-610

**Comment by llibarona** [comment]
this should be fixed in stable version 5.0.0
