### ISSUE TITLE
Question: some queries about OAS 3.1.x support and adding new dialects

### ISSUE THREAD

**Issue by LuisTejedaS** [aml-org/als#687]
Your issue may already be reported! Please search on Github issues before creating one.

* **I'm submitting a ...**
    - [ ] bug report
    - [ ] feature request
    - [X] question
    - [ ] other

* **What is the current behavior?**
We have support for OAS 2.x and 3.0.x

* **If the current behavior is a bug, please provide the minimal steps to reproduce on ALS**
It is not a bug
* **Please provide stack traces/logs and the failing JSON rpc message if possible**
no needed
* **File being edited (API spec/AML Document)**
N/A
* **What is the expected behavior?**
N/A
* **What is the motivation/use case for changing the behavior? (for feature requests)**
Adding support for 3.1.x due that this version has some breaking changes
* **Please tell us about your environment:**
N/A
* **Other information** 

Hi, first of all thanks for your effort providing this amazing tools.
I have a couple of questions:

First: are you planning to add support for OAS 3.1.X? As this new version has some braking changes against 3.0.X
Second: how much effort do you think adding support for a new dialect like OAS 3.1.X will take? And briefly what steps need to be done to add this new dialect natively (no registering via command)?

**Comment by llibarona** [comment]
Hi @LuisTejedaS !
sorry for the delay
we are definitely planning on supporting this version in the future, but right now I cannot provide you with specific dates, as we are still planning the roadmap and this involves more than one team.
In order for ALS to support OAS 3.1.x, first [AMF](https://github.com/aml-org/amf/) needs to support it
Once implemented in AMF, we can adopt this changes and write a Dialect with the specifics in order to have complete tooling
I will leave this ticket open for a while, so I can check if we (ALS or AMF team) can define some approximated dates and let you know

In order to run a dialect natively, it would be necessary to touch some code (check for example `BaseAlsDialectProvider` which contains our WebAPI dialects), In case of writing this dialect in YAML you can see an example with `InMemoryDialect` on how to parse it for registering.
The problem with WebAPI specs is that they are not entirely representable with Dialects, so some specific hacks are needed in order to provide a full fledged experience.

Please let me know if there is anything else we can help you with, and as soon as I have more info about 3.1.x support I will let you know!

**Comment by llibarona** [comment]
@LuisTejedaS I talked to the related teams, and there is no immediate plan to implement OAS 3.1.x, it is assumed it will be done this FY, but it has not yet been prioritized
Sorry for this inconvenience
Best regards!

**Comment by LuisTejedaS** [comment]
@llibarona thanks for your answer and all the information, kind regards.
